# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TicTacToeTest' do
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'master'
    pod 'Alamofire', '~> 3.2'

end

