# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'ChartsTest' do
pod 'Charts', '~> 2.2'

end

target 'ChartsTestTests' do

end

target 'ChartsTestUITests' do

end

